# Generated by Django 2.2.6 on 2019-10-31 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=300)),
                ('status', models.IntegerField(default=0)),
                ('pub_date', models.DateTimeField(verbose_name='published date and time')),
            ],
        ),
    ]
