# Generated by Django 2.2.6 on 2019-11-02 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20191102_0852'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todolist',
            old_name='status',
            new_name='visible',
        ),
    ]
