# Generated by Django 2.2.6 on 2019-11-02 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20191102_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='published date and time'),
        ),
    ]
