# Generated by Django 2.2.6 on 2019-12-02 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_auto_20191103_0258'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
